---
title: "Assignment 6"
author: "Camilla Salwen"
date: "2023-01-23"
output: html_document
---

```{r}
library(tidyverse)
```

1. 150 observations, 5 variables
```{r}
str(iris)
```


2. 56 obs of 5 variables
```{r}
iris1 <- filter(iris, Species == "versicolor"|Species == "virginica", Sepal.Length > 6, Sepal.Width > 2.5) 

```

3. 56 obs of 3 variables
```{r}
iris2 <- select(iris1, Sepal.Width, Sepal.Length, Species)
```

4.
```{r}
iris3 <- arrange(iris2, by = desc(Sepal.Length))
head(iris3)
```

5. 56 obs of 4 variables
```{r}
iris4 <- mutate(iris3, sepal_area = Sepal.Length*Sepal.Width)
```

6. 
```{r}
irisTab <- summarize(iris4, mean_sepal_length = mean(Sepal.Length), mean_sepal_width = mean(Sepal.Width), sample_size = n())
print(irisTab)
```

7. Finally, create iris5 that calculates the average sepal length, the average sepal width, and the sample size for each species of in the iris4 data frame and print iris5.
```{r}
iris5 <- summarize(group_by(iris4, Species), mean_sepal_length = mean(Sepal.Length), mean_sepal_width = mean(Sepal.Width), sample_size = n())
print(iris5)
```

8. 

```{r}
iris_final <- iris %>%
  filter(Species == "versicolor"|Species == "virginica", Sepal.Length > 6, Sepal.Width > 2.5) %>%
  select(Sepal.Width, Sepal.Length, Species) %>%
  arrange(by = desc(Sepal.Length)) %>%
  mutate(sepal_area = Sepal.Length*Sepal.Width) %>%
  group_by(Species) %>%
  summarize(mean_sepal_length = mean(Sepal.Length), mean_sepal_width = mean(Sepal.Width), sample_size = n())
  
  
```



