---
title: "Assignment 4"
author: "Camilla Salwen"
date: "2023-01-17"
output: html_document
---

## Question 1

```{r}
n_dims <- sample(3:10, 1)

cons_int <- 1:(n_dims)^2

elements <- sample(cons_int)

mat <- matrix(data = elements, nrow = n_dims, ncol = n_dims)

print(mat)

transposed <- t(mat)

print(transposed)
# numbers are swapped diagonally, row is column and column is row

sum(mat[1,])
mean(mat[1,])

sum(mat[n_dims,])
mean(mat[n_dims,])


```

## Question 2
```{r}
my_matrix <- matrix(data = runif(16), nrow = 4, ncol = 4)
my_logical <- c((runif(100) > 0.5))
my_letters <- sample(c(letters))


my_list <- list(my_matrix = my_matrix, my_logical = my_logical, my_letters = my_letters)

new_list <- list(my_list$my_matrix[2,2], my_list$my_logical[2], my_list$my_letters[2])

typeof(new_list[[1]])

typeof(new_list[[2]])

typeof(new_list[[3]])

vec <- unlist(new_list)

typeof(vec)

```

## Question 3
```{r}

my_unifs <- runif(26, min = 0, max = 10)
my_Letters <- sample(c(LETTERS))

data_frame <- data.frame(my_unifs = my_unifs, my_Letters = my_Letters)

data_frame$my_unifs[sample(1:26, 4)] <- NA

complete.cases(data_frame$my_unifs)

ordered_data_frame <- data_frame[order(data_frame$my_Letters), ]

mean(data_frame[,"my_unifs"], na.rm = TRUE)

colnames(ordered_data_frame)[2] <- "my_LETTERS"

head(ordered_data_frame)

```


