---
title: "Weekly Assignment 1"
author: "Camilla Salwen"
date: "2023-01-16"
output:
  prettydoc ::html_pretty:
    theme: leonids
    highlight: github
---

# Setting up a GitHub web page!!

### Step 1: Create a GitHub account
Go to [Github](https://github.com/) and create a new account
  
### Step 2: Installing git in RStudio
This can be a challenging step depending on the computer so patience is key!

For macs, install [homebrew](https://brew.sh/) from your browser. Make sure you have a good wifi connection, otherwise it will take forever.

* search your computer for terminal and open it
* paste the link from the homebrew site into terminal
* input the password to your computer (it's ok if nothing shows while you are typing, it's working!)
* you'll know homebrew is done installing when the last line shown in terminal shows your username and a % at the end
* if it's not working, try installing XCodes from the app store, then do homebrew

Next, type **brew install git** into terminal. You'll know it's done the same way as before.

### Step 3: Create a repository in GitHub

* log in on GitHub
* click on *create new repository* on the left side of the home page
* name your repo, then:
  + make sure it is **public**
  + add a **README** file
  + there is **none** set for gitignore
  + license chosen is **MIT**
* once it is created, go to *pages*, found on the left side of the page, and select **main** under Branch

## Step 4: Credentials for linking RStudio to GitHub

### Step 5: Linking your GitHub Repo to RStudio

**In GitHub:**

* on the home page of your repo, click on the green box
* copy the URL from there

**In RStudio:**

* click on the upper right corner and select *new project*
* select *Version Control* on the popup window
* select *Git*
* paste the URL copied from GitHub into the top box
* name your project the same exact name as your repo in the next box
* select where to save it (not downloads!)
* hit **create project**!

### Step 6: Create Index

* in RStudio, click on the plus page icon in the upper left corner, and select RMarkdown
* name it index, select HTML, and hit create
* everything below the second set of three dashes (- - -), can be deleted and replaced with your own materials
* save and knit your file, naming it index

### Step 7: Upload to GitHub

* in RStudio terminal, type **git status**
  + there should be your index file written in red
* type **git add -A**
  + after you do this, you can check **git status** again, the file name should have turned green
* then, type **git commit -am "notes"**
* finally, **git push**

After a minute or two, your web page should be up! In your browser, type in: username.github.io/repo/ and you should get to your page. For example, this is mine: [https://csalwen.github.io/BIOL1007A/](https://csalwen.github.io/BIOL1007A/)

## Congrats! You're done!

