---
title: "Assignment 3"
author: "Camilla Salwen"
date: "2023-01-12"
output: html_document
---

### Question 1
```{r}
x <- 1.1
a <- 2.2
b <- 3.3

z <- x^a^b
print(z)

## [1]   1.233286   1.586137   2.758985   9.324992 135.902257

z <- (x^a)^b
print(z)

## [1] 1.233286 1.520995 1.875822 2.313426 2.853117

z <- 3*x^3 + 2*x^2 + 1 
print(z)

## [1] 7.413
```

### Question 2
```{r}
first <- c(seq(from = 1, to = 8), seq(from = 7, to = 1)) 
# or c(1:8, 7:1)

b <- rep(x = 1:5)
second <- rep(x = 1:5, times = b)

c <- rep(x = 1:5)
third <- rep(x = 5:1, times = c)

```

### Question 3
```{r}
queue <- c("sheep", "fox", "owl", "ant")

queue <- c(queue[1:4], "serpent")
# or queue[5] <- "serpent"
## [1] "sheep"   "fox"     "owl"     "ant"     "serpent"

queue <- c(queue[2:5])
## [1] "fox"     "owl"     "ant"     "serpent"

queue <- c("donkey", queue[1:4])
## [1] "donkey"  "fox"     "owl"     "ant"     "serpent"

queue <- c(queue[1:4])
# or queue <- queue[-5]
## [1] "donkey" "fox"    "owl"    "ant"

queue <- append(queue, "aphid", after = 3)
## [1] "donkey" "fox"    "owl"    "aphid"  "ant"

which(queue == "aphid")
## [1] 4
```


